# Generated by Django 3.1.6 on 2021-02-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210206_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_attributes',
            name='user',
            field=models.IntegerField(default='1'),
        ),
    ]
