# Generated by Django 3.1.6 on 2021-02-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210206_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_attributes',
            name='user',
            field=models.IntegerField(default='1'),
        ),
    ]
