# Generated by Django 3.1.6 on 2021-02-07 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_hospital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='available_beds',
            new_name='available_Vaccine',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='total_beds',
            new_name='total_Vaccine',
        ),
    ]
