# Generated by Django 3.1.6 on 2021-02-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210207_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('hospital', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('fulfilled', models.BooleanField()),
                ('confirmtime', models.CharField(max_length=50)),
            ],
        ),
    ]
